### ISSUE TITLE
Add feature flag support

### ISSUE THREAD

**Issue by Rahul-D78** [kubeslice/worker-operator#293]
Feature flags, also known as feature toggles, are a critical feature for managing feature releases and controlling the activation or deactivation of specific functionalities. This feature will provide greater flexibility, control, and safety in our deployment and release processes. 

### Implementation Options:
There are multiple ways to implement feature flags such as:
* Dedicated tool like [openfeature](https://openfeature.dev/)
* Kubernetes ConfigMaps or custom resources to store feature flag configurations.
* Using environment variables to control feature flag states.
* Configure it as a GO command line flag.

```golang
opts := zap.Options{
  Development: true,
}
opts.BindFlags(flag.CommandLine)

// combine both flagsets and parse them
pflag.CommandLine.AddGoFlagSet(flag.CommandLine)
features.OperatorFeatureGate.AddFlag(pflag.CommandLine)
pflag.Parse()
```
This way, the feature flags can be configured runtime via flags in managers deployment manifest.
```yaml
 containers:
  - command:
    - /manager
    args:
    - --leader-elect
    - --feature-gates=FeatureName=true
    - --feature-gates=FeatureName=false
```
